name: Run FastAPI Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Set up virtual environment and install dependencies
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv pip install --group default

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest tests/
